// Try catch

const number1 = 20;
const number3 = 40;

console.log(number1);

try {
    console.log(number2);
} catch (error) {
    console.log(error);
}

console.log(number3);